# Generated by Django 2.2.2 on 2019-08-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_book_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='list',
        ),
        migrations.AddField(
            model_name='lists',
            name='book',
            field=models.ManyToManyField(to='listas.Book'),
        ),
    ]
