# Generated by Django 2.2.2 on 2019-08-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0006_auto_20190807_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.ManyToManyField(to='listas.Lists'),
        ),
    ]
