# Generated by Django 2.2.2 on 2019-08-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0007_auto_20190810_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='list',
        ),
    ]
