# Generated by Django 2.2.2 on 2019-08-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0008_auto_20190810_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listas.Gender'),
        ),
    ]
