# Generated by Django 2.2.2 on 2019-10-08 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listas', '0011_auto_20190812_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='userlist',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
